---
- name: Create grafana folder
  file: 
    path: "{{ PATH }}/grafana"
    mode: '0755'
    state: directory
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
  become: true

- name: Create datasource folder
  file:
    path: "{{ PATH }}/grafana/provisioning/datasources/"
    mode: '0755'
    state: directory
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
  become: true

- name: Generate config
  template:
    src: grafana/grafana.ini.j2
    dest: "{{ PATH }}/grafana/grafana.ini"
    mode: '0744'
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
  become: true

- name: Generate LDAP
  template:
    src: grafana/ldap.toml.j2
    dest: "{{ PATH }}/grafana/ldap.toml"
    mode: '0744'
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
  become: true
  when: grafana_ldap.enable == true

- name: Generate datasource
  template:
    src: grafana/datasources.yml.j2
    dest: "{{ PATH }}/grafana/provisioning/datasources/ansible.yml"
    mode: '0744'
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
  become: true
