---
- name: Create config folder
  file:
    path: "{{ PATH }}/loki"
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
    state: directory
    mode: '0755'
  become: true

- name: Generate loki conf
  template:
    src: loki/loki.conf.j2
    dest: "{{ PATH }}/loki/loki.conf"
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
    mode: '0744'
  become: true

- name: Generate promtail conf
  template:
    src: loki/promtail.conf.j2
    dest: "{{ PATH }}/loki/promtail.conf"
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
    mode: '0744'
  become: true

- name: Generate syslog conf
  template:
    src: loki/syslog-ng.conf.j2
    dest: "{{ PATH }}/loki/syslog-ng.conf"
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
    mode: '0744'
  become: true
