---
- name: Setup role
  include_tasks: "setup.yml"

- name: Configure prometheus
  include_tasks: prometheus.yml

- name: Configure loki
  include_tasks: loki.yml

- name: Configure grafana
  include_tasks: grafana.yml

- name: Configure uglymap
  include_tasks: uglymap.yml

- name: Start app
  include_tasks: "start.yml"
