---
- name: Create prometheus folder
  file:
    path: "{{ PATH }}/prometheus"
    mode: '0755'
    state: directory
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
  become: true

- name: Create rule folder
  file:
    path: "{{ PATH }}/prometheus/rules"
    mode: '0755'
    state: directory
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
  become: true

- name: Generate conf
  template:
    src: prometheus/prometheus.yml.j2
    dest: "{{ PATH }}/prometheus/prometheus.yml"
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
    mode: '0744'
  become: true

- name: Copy alert
  copy:
    src: alert.rules.yml
    dest: "{{ PATH }}/prometheus/rules/rules.yml"
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
    mode: '0744'
  become: true
