---
- name: Create monitoring user
  user:
    name: "{{ USER.USERNAME }}"
    shell: "{{ USER.SHELL }}"
    create_home: "{{ USER.CREATE_HOME }}"
    state: present
    uid: "{{ USER.UID }}"
  become: true

- name: Create folder
  file:
    path: "{{ PATH }}"
    mode: '0755'
    state: directory
    owner: "{{ USER.USERNAME }}"
    group: "{{ USER.USERNAME }}"
  become: true

- name: Install packages
  apt:
    name:
      - python3-pip
      - docker-compose
    state: present