---
version: "3"

networks:
  loki:

services:
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng
    environment:
      - PUID=1030
      - PGID=1030
      - TZ=America/Toronto
    volumes:
      - /opt/loki/syslog-ng.conf:/config/syslog-ng.conf
    networks:
      - loki
    ports:
      - 5514:5514/udp
      #- 6601:6601/tcp
      #- 6514:6514/tcp
    restart: unless-stopped
  
  loki:
    image: grafana/loki
    command: -config.file=/etc/loki/loki.conf
    ports:
      - 3100:3100
    volumes:
      - /opt/loki/loki.conf:/etc/loki/loki.conf
    restart: unless-stopped
    networks:
      - loki

  promtail:
    image: grafana/promtail
    ports:
      - 9080:9080
      - 1514:1514
    volumes:
      - /opt/loki/promtail.conf:/etc/promtail/promtail.conf
    command: -config.file=/etc/promtail/promtail.conf
    networks:
      - loki
    restart: unless-stopped
